[package]
name = "almost-zk"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
ark-bn254 = "0.5.0"
ark-std = "0.5.0"
ark-ec = "0.5.0"
ark-ff = "0.5.0"
ark-serialize = { version = "0.5.0", features = ["derive"] }
